# Generated by Django 3.1 on 2020-08-15 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_category', models.CharField(choices=[('CONFERENCE', 'CONFERENCE'), ('SEMINAR', 'SEMINAR'), ('CONGRESS', 'CONGRESS'), ('COURSE', 'COURSE')], max_length=10)),
                ('event_place', models.CharField(max_length=255)),
                ('event_address', models.CharField(max_length=255)),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('VIRTUAL', 'VIRTUAL'), ('PRESENCIAL', 'PRESENCIAL')], max_length=10)),
                ('thumbnail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
