# Generated by Django 3.1 on 2020-08-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='password',
        ),
    ]
