# Generated by Django 3.1 on 2020-08-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apiuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUser',
        ),
    ]
